### ISSUE TITLE
有关.hex文件的问题

### ISSUE THREAD

**Issue by Reset816** [addrices/RISCV-TESTFRAMEWORK#2]
您好，我想请教一下`.hex`文件里的`@`符号是什么意义呢？[lb_d.hex](https://github.com/addrices/RISCV-TESTFRAMEWORK/blob/3_916/testcase/lb_d.hex)甚至还在文件中间有个`@`。

此外您提到_d.hex是dmem中的内容，那lb_d.hex有24行是不是指有24*32位的数据？

**Comment by addrices** [comment]
@后面的是地址，再之后是数据

**Comment by addrices** [comment]
可以到git@github.com:addrices/riscv-tests.git的目录下的[Makefile](https://github.com/addrices/riscv-tests/blob/master/isa/Makefile)查看编译过程（line53-59）

**Comment by Reset816** [comment]
明白了 谢谢
